#!/usr/bin/env Rscript

# This script takes a table generated by the script
# 'identify_hotizontal_transfers.R', and a table containing the full lineage
# of the species represented in the table as input, and returns a
# list containing the taxonomic difference (order- class- or phylum-level)
# between the orders represented in each event.

#-------------------------------------------------------------------------------
# 0 LOAD LIBRARIES
#-------------------------------------------------------------------------------
library(caret)
library(dplyr)
library(forcats)
library(data.table)
library(Dict)
library(optparse)

#-------------------------------------------------------------------------------
# 1 INPUT ARGUMENTS
#-------------------------------------------------------------------------------
option_list <- list(
  make_option(c("--taxonomy"), type = "character", default = NULL,
              help = "Table containing complete taxonomic lineages", metavar = "character"),
  make_option(c("-i", "--input"), type = "character", default = NULL,
              help = "Table created by 'indentify_horizontal_transfers.R'", metavar = "character"),
  make_option(c("-o", "--output"), type = "character", default = NULL,
              help = "Output file name", metavar = "character")
)
 
opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$taxonomy) | is.null(opt$input) | is.null(opt$output)) {
  print_help(opt_parser)
  stop("ERROR: Missing input argument(s)", call. = FALSE)
}


args <- commandArgs(trailingOnly = TRUE)
input_filename <- as.character(args[1])
taxonomy_table <- as.character(args[2])
output_filename <- as.character(args[3])

#-------------------------------------------------------------------------------
# 2 DEFINE FUNCTIONS
#-------------------------------------------------------------------------------
setup.dictionary <- function(path) {
    table <- read.table(path, sep = "\t")
    colnames(table) <- c("phylum", "class", "order")
    table <- table[!is.na(table$class), ]

    taxonomy <- Dict$new(
        token = 0,
        .overwrite = TRUE
    )

    for (i in seq_len(nrow(table))) {
        taxonomy[as.character(table$order[i])] = c(as.character(table$phylum[i]), as.character(table$class[i]))
    }
}

measure.taxonomic.difference <- function(order1, order2, taxonomy) {
    if (!(order1 %in% taxonomy$keys) || !(order2 %in% taxonomy$keys)){
        tax_level_diff <- NA
        return(tax_level_diff)

    } else {
        tax1 <- taxonomy[order1]
        tax2 <- taxonomy[order2]

        if (is.na(tax1[1]) || is.na(tax2[1])) {
            tax_level_diff <- NA

        } else if (tax1[1] != tax2[1]){
            tax_level_diff <- "phylum"

        } else if (tax1[2] != tax2[2]){
            tax_level_diff <- "class"

        } else{
            tax_level_diff <- "order"
        }

        return(tax_level_diff)
    }
}

#-------------------------------------------------------------------------------
# 3 MEASURE TAXONOMIC DIFFERENCE
#-------------------------------------------------------------------------------
taxonomy <- setup.dictionary(opt$taxonomy)
horizontal_transfers <- data.frame(fread(opt$input))

order1 <- horizontal_transfers$Order1
order2 <- horizontal_transfers$Order2

tax_level_diff <- c()

for (i in seq_len(nrow(horizontal_transfers))) {
    tax_level_diff[i] <- measure.taxonomic.difference(order1[i], order2[i], taxonomy)
}

write.table(tax_level_diff, opt$output, quote=FALSE, row.names=FALSE, col.names=FALSE)
